---
- name: demo
  hosts: test1.example.com
   
  vars:
   var1: 
    - a.txt
    - b.txt
   var2: 
    - c.txt
    - d.txt
   mygroup:
    - "{{var1}}}"
    - "{{var2}}}"
  tasks:
   - name: display
     debug:
      msg: "{{item}}"
     loop: "{{mygroup}}"
     #loop: "{{mygroup}}"
     #with_items: "{{mygroup}}"
     #loop: "{{myfiles}}"
     #with_nested: "{{myfiles}}"
...
