---
  - name: install httpd
    ansible.builtin.yum: name=httpd state=latest
  - name: start and enable httpd
    ansible.builtin.service: name=httpd state=started enabled=true
  - name: Deliver html content
    ansible.builtin.copy: src=html/ dest=/var/www/vhosts/{{ ansible_hostname }}
  - name: Printout
    ansible.builtin.debug: 
     msg: "{{mypkg1}}"
  - name: Template vhost file
    ansible.builtin.template: src=vhost.conf.j2 dest=/etc/httpd/conf.d/vhost.conf owner=root group=root mode=0644
    notify:
      - restart_httpd
   


