---
- hosts: servera.lab.example.com
  become: yes
  tasks:
  - name: Add multiple repositories into the same file (1/1)
    yum_repository:
      name: ansible 
      description: Ansible Repository
      file: ansible
      baseurl: http://content.example.com/ansible2.3/x86_64/dvd/2.3/
      gpgcheck: no
      enabled: yes
  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: rhel_dvd 
      description: Remote classroom copy of dvd
      file: rhel_dvd
      baseurl: http://content.example.com/rhel7.3/x86_64/dvd 
      gpgcheck: no
      enabled: yes

...
