---
  - name: install httpd
    yum: name=httpd state=latest
    tags:
     - gls
  - name: start and enable httpd
    service: name=httpd state=started enabled=true
  - name: Deliver html content
    copy: src=html/ dest=/var/www/vhosts/{{ ansible_hostname }}
  - name: Template vhost file
    template: src=vhost.conf.j2 dest=/etc/httpd/conf.d/vhost.conf owner=root group=root mode=0644
    notify:
      - restart_httpd
   


