---
- name: demo-strings-linebreak-and-retain
  hosts: east
  vars:
   answer: 42
   float_answer: 42.0 
   scientific_answer: 0.42e+2
   hex_answer: 0x2A
   string_not_number: "20"
   mybool: true
   myundefined1: ~
   myundefined2: null
   my_date_time: 2022-01-30T21:15:32.42+02:00
   my_simple_date: 2022-01-18
   
  tasks:
   - name: Diplay
     debug: 
      msg: "{{answer}} {{float_answer}} {{scientific_answer}} {{hex_answer}} {{string_not_number}} {{mybool}} {{myundefined1}} {{myundefined2}} {{my_date_time}} {{my_simple_date}}"
...
