---
#inventory
#playbook
#task
#group_var
#host_vars
#role -vars,default

- name: Demo
  hosts: all
  tasks:
   - name: Display1
     debug:
      msg: "{{inventory_hostname}} {{ansible_hostname}} {{ansible_fqdn}}"
...
