- name: demo
  hosts: test1.example.com
  tasks:
   - name: Display1
     debug:
      msg: "{{lookup('dig', 'google.com')}}"
   - name: Display2
     debug:
      msg: "{{ lookup('dig', 'google.com', 'qtype=MX') }}"
   - name: Display3
     debug:
      msg: "{{ lookup('dig', 'google.com/SOA') }}"
   - name: Display4
     debug:
      #msg: "{{ lookup('dnstxt', ['www.redhat.com']) }}"
      msg: "{{ lookup('dig', 'google.com/TXT') }}"
  
 
